List<Map<String, dynamic>> misObj = [
  {"textoX": "Snuffle 🤧", "iconX": 1},
  {"textoX": "High Fever 🤒️", "iconX": 1},
  {"textoX": "Nauseous 🤮", "iconX": 1},
  {"textoX": "Snuffle 🤧", "iconX": 1},
  {"textoX": "High Fever 🤒️", "iconX": 1},
  {"textoX": "Nauseous 🤮", "iconX": 1},
  {"textoX": "Snuffle 🤧", "iconX": 1},
  {"textoX": "High Fever 🤒️", "iconX": 1},
  {"textoX": "Nauseous 🤮", "iconX": 1},
  {"textoX": "Snuffle 🤧", "iconX": 1},
  {"textoX": "High Fever 🤒️", "iconX": 1},
  {"textoX": "Nauseous 🤮", "iconX": 1},
  {"textoX": "Snuffle 🤧", "iconX": 1},
  {"textoX": "High Fever 🤒️", "iconX": 1},
  {"textoX": "Nauseous 🤮", "iconX": 1},
  {"textoX": "Snuffle 🤧", "iconX": 1},
  {"textoX": "High Fever 🤒️", "iconX": 1},
  {"textoX": "Nauseous 🤮", "iconX": 1},
  {"textoX": "Snuffle 🤧", "iconX": 1},
  {"textoX": "High Fever 🤒️", "iconX": 1},
  {"textoX": "Nauseous 🤮", "iconX": 1},
  {"textoX": "Snuffle 🤧", "iconX": 1},
  {"textoX": "High Fever 🤒️", "iconX": 1},
  {"textoX": "Nauseous 🤮", "iconX": 1},
];
